version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "56:e5:64:2a:56:37:10:6d:a2:72:0d:aa:ed:ae:d7:7f"
      - checkout
      - restore_cache:
          keys:
            - dependencies_exam_management
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_exam_management
      - run:
          name: Build
          command: yarn build:prod
      - run:
          name: Run Deploy to HWServer
          command: |
            ssh $SSH_USER@$SSH_HOST "scp -r '../${siteSource}/.' root@139.159.201.22:/root/www/ExamManagement"
